data_2 = [{"category": "Science: Computers",
           "type": "boolean",
           "difficulty": "medium",
           "question": "The HTML5 standard was published in 2014.",
           "correct_answer": "True",
           "incorrect_answers": ["False"]
           },
          {"category": "Science: Computers",
           "type": "boolean",
           "difficulty": "medium",
           "question": "The common software-programming acronym 'I18N' comes from the term 'Interlocalization'.",
           "correct_answer": "False",
           "incorrect_answers": ["True"]},
          {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
           "question": "The first computer bug was formed by faulty wires.",
           "correct_answer": "False", "incorrect_answers": ["True"]},
          {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
           "question": "'Windows NT' is a monolithic kernel.",
           "correct_answer": "False", "incorrect_answers": ["True"]},
          {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
           "question": "MacOS is based on Linux.", "correct_answer": "False",
           "incorrect_answers": ["True"]},
          {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
           "question": "The open source program Redis is a relational database server.",
           "correct_answer": "False", "incorrect_answers": ["True"]},
          {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
           "question": "The first dual-core CPU was the Intel Pentium D.",
           "correct_answer": "False", "incorrect_answers": ["True"]},
          {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
           "question": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
           "correct_answer": "False", "incorrect_answers": ["True"]},
          {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
           "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
           "correct_answer": "False", "incorrect_answers": ["True"]},
          {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
           "question": "A Boolean value of '0' represents which of these words?",
           "correct_answer": "False", "incorrect_answers": ["True"]}]
